### Tomcat server listening port
server:
    port: 8000

### Spring boot logging level
# logging:
#     level:
#         org:
#             springframework: DEBUG

# database:
#     driver-class-name: org.mariadbc.jdbc.Driver
#     url: jdbc:mariadb://localhost:3306/board
#     username: root
#     password: 123456