---
### Common settings for Spring Boot

# Spring Boot options
spring:
    devtools:
        livereload:
            enabled: false
    profiles:
        active: local
    # JPA Options Setting
    jpa:
        open-in-view: false
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
    # Spring Boot output log colorize
    output:
        ansi:
            enabled: always
    
###