### Tomcat server listening port
server:
    port: 8000

### Spring boot logging level
# logging:
#     level:
#         org:
#             springframework: DEBUG

### Spring DataSource
IP:
    DATABASE_IP: localhost