spring:
    devtools:
        livereload:
            enabled: false
    profiles:
        active: local
    output:
        ansi:
            enabled: always
    sql:
        init:
            # Active initializing script for all target database
            mode: always
            # .sql file (schema) location
            schema-locations: classpath:schema-mariadb.sql
            data-locations: classpath:data-mariadb.sql

# Spring Doc OpenAPI Configuration
springdoc:
    packages-to-scan: com.boardapp.boardapi
    # Config Contents Media Type
    default-consumes-media-type: application/json;charset=UTF-8
    default-produces-media-type: application/json;charset=UTF-8
    swagger-ui:
        path: /swagger-ui.html               # Swagger UI Route Path : http://localhost:<Port Num.>/swagger-ui.html
        disable-swagger-default-url: true
        display-request-duration: true
        tags-sorter: alpha                  # alpha: Tag sort by alphanumeric, method: Sort by HTTP Method 
        operations-sorter: method            # alpha: Tag sort by alphanumeric, method: Sort by HTTP Method
    api-docs:
        path: /api-docs/json
        groups:
            enabled: true
    cache:
        disabled: true
###