---
# Common settings for Spring Boot

# Server Runnin Port
server:
    port: 8000

# Spring Boot options
spring:
    devtools:
        livereload:
            enabled: false
    profiles:
        active: @spring.profiles.active@ 
    # JPA Options Setting
    jpa:
        open-in-view: false
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
    # Spring Boot output log colorize
    output:
        ansi:
            enabled: always

---
# Local Environment Setting
spring:
    # Profile Name
    # Same configuration with application-local.yaml
    config:
        activate:
            on-profile: local
    # JPA Connection Setting
    datasource:
        # Database : MariaDB
        driver-class-name: org.mariadb.jdbc.Driver
        # URL IP link to localhost
        url: jdbc:mariadb://localhost:3306/board?characterEncoding=UTF-8&serverTimezone=UTC
        # Database username
        username: root
        # Database user password
        password: 123456

---
# Docker Container Environment Setting
spring:
    # Profile Name
    # Same configuration with application-dev.yaml
    config:
        activate:
            on-profile: dev
    # JPA Connection Setting
    datasource:
        # Database : MariaDB
        driver-class-name: org.mariadb.jdbc.Driver
        # URL IP link to container name
        url: jdbc:mariadb://mariadb:3306/board?characterEncoding=UTF-8&serverTimezone=UTC
        # Database username
        username: root
        # Database user password
        password: 123456

---
# Kubernetes Deployment Environment Setting
spring:
    # Profile Name
    # Same configuration with application-prod.yaml
    config:
        activate:
            on-profile: prod
    # JPA Connection Setting
    datasource:
        # Database : MariaDB
        driver-class-name: org.mariadb.jdbc.Driver
        # URL IP link to local container db
        url: jdbc:mariadb://host.docker.Inner:3306/board?characterEncoding=UTF-8&serverTimezone=UTC
        # Database username
        username: root
        # Database user password
        password: 123456