---
# Common settings for Spring Boot

# Server Runnin Port
server:
    port: 8000

# Spring Boot options
spring:
    devtools:
        livereload:
            enabled: false
    profiles:
        active: @spring.profiles.active@ 
    # JPA Options Setting
    jpa:
        open-in-view: false
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
    # Spring Boot output log colorize
    output:
        ansi:
            enabled: always

---
# Local Environment Setting
spring:
    # Profile Name
    # Same configuration with application-local.yaml
    config:
        activate:
            on-profile: local
    profile:
        include:
        - local

---
# Docker Container Environment Setting
spring:
    # Profile Name
    # Same configuration with application-dev.yaml
    config:
        activate:
            on-profile: dev
    profile:
        include:
        - container

---
# Kubernetes Deployment Environment Setting
spring:
    # Profile Name
    # Same configuration with application-prod.yaml
    config:
        activate:
            on-profile: prod
    profile:
        include:
        - kubernetes